server:
  port: 8080

spring:
  application:
    name: Spring_Keycloak

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_keycloak?serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

keycloak:
  realm: learn-oauth2-keycloak
  auth-server-url: http://localhost:8050
  resource: oauth2-demo-thymeleaf-client
  public-client: true
  bearer-only: true